### ISSUE TITLE
amda ace imf column names

### ISSUE THREAD

**Issue by nicolasaunai** [SciQLop/speasy#132]
* Speasy version:1.2.7
* Python version:3.10.xxx
* Operating System:mac

### Description

Can't reproduce a plot of the documentation

### What I Did

```python
import matplotlib.pyplot as plt
from datetime import datetime
%matplotlib widget

plt.figure()
ace_mag = spz.get_data(spz.inventories.data_tree.amda.Parameters.ACE.MFI.ace_imf_all.imf, datetime(2016,6,2), datetime(2016,6,5))
ace_mag.plot()
plt.tight_layout()
plt.show()
```

I get : 

<img width="627" alt="image" src="https://github.com/SciQLop/speasy/assets/3200931/a10111d6-0771-4f21-b98d-8601ae602de3">

Column names are `['bx', 'by', 'bz']` whereas they are imf[0] etc. on documentation.

**Comment by nicolasaunai** [comment]
tested the documentation page on Binder, gives me bx, by bz too.
AMDA web GUI seems to propose also bx, by bz

Weird thing that pushed me to write this issue is that Vincent G. has imf[0] etc: 

```
spz.get_data('amda/imf', "2016-6-2", "2016-6-5",disable_cache=True, disable_proxy=True ).columns
Out[83]: ['imf[0]', 'imf[1]', 'imf[2]']
```

**Comment by nicolasaunai** [comment]
automagically "solved" with `pip install —user --upgrade --force-reinstall speasy` 
weird.

**Comment by vgenot** [comment]
strangely @nicolasaunai and myself yesterday had spz.__version__ = 1.1.2
after reinstall I have spz.__version__ = 1.2.7

**Comment by nicolasaunai** [comment]
yeah well I think I made a typo, I had 1.2.2 :/
So the reinstall did indeed solved your "issue" (which really was not an issue but just that you had an older version than 1.2.0 installed).
