### ISSUE TITLE
Laoding speasy issue

### ISSUE THREAD

**Issue by Nfargette** [SciQLop/speasy#150]
* Speasy version: 1.2.4
* Python version: 3.9.13
* Operating System: windows

### Description
speasy is not loading today ? (was working last week)

### What I Did : 

import speasy           as spz

INFO: Query finished. [astroquery.utils.tap.core]
INFO: Query finished. [astroquery.utils.tap.core]
INFO: Query finished. [astroquery.utils.tap.core]
INFO: Query finished. [astroquery.utils.tap.core]
INFO: Query finished. [astroquery.utils.tap.core]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
c:\Users\nfargett\.vscode\ipython\code.py in <module>
----> 1 import speasy           as spz

~\Anaconda3\lib\site-packages\speasy\__init__.py in <module>
     19
     20 # keep this import last
---> 21 from .core.requests_scheduling.request_dispatch import get_data, list_providers, amda, cda, csa, ssc, archive
     22
     23

~\Anaconda3\lib\site-packages\speasy\core\requests_scheduling\__init__.py in <module>
      1 from .split_large_requests import SplitLargeRequests
----> 2 from .request_dispatch import get_data

~\Anaconda3\lib\site-packages\speasy\core\requests_scheduling\request_dispatch.py in <module>
     58 if not core_cfg.disabled_providers().intersection({'ssc', 'sscweb'}):
     59     if is_server_up(SSC_Webservice.BASE_URL):
---> 60         ssc = SSC_Webservice()
     61         sys.modules[__name__].ssc = ssc
     62         PROVIDERS['ssc'] = ssc

~\Anaconda3\lib\site-packages\speasy\webservices\ssc\__init__.py in __init__(self)
     74     def __init__(self):
     75         self.__url = f"{self.BASE_URL}/WS/sscr/2"
---> 76         DataProvider.__init__(self, provider_name='ssc', provider_alt_names=['sscweb'])
     77
     78     def build_inventory(self, root: SpeasyIndex):

~\Anaconda3\lib\site-packages\speasy\core\dataprovider.py in __init__(self, provider_name, provider_alt_names, inventory_disable_proxy)
     46         for alt_name in self.provider_alt_names:
     47             flat_inventories.__dict__[alt_name] = self.flat_inventory
---> 48         self.update_inventory()
     49         PROVIDERS[provider_name] = self
     50

~\Anaconda3\lib\site-packages\speasy\core\dataprovider.py in update_inventory(self)
     61         lock = Lock()
     62         with lock:
---> 63             new_inventory = self._inventory(provider_name=self.provider_name,
     64                                             disable_proxy=self._inventory_disable_proxy)
     65             if inventory_has_changed(tree.__dict__.get(self.provider_name, SpeasyIndex("", "", "")), new_inventory):

~\Anaconda3\lib\site-packages\speasy\core\proxy\__init__.py in wrapped(*args, **kwargs)
    139                 except:  # lgtm [py/catch-base-exception]
    140                     log.error(f"Can't get data from proxy server {proxy_cfg.url()}")
--> 141             return func(*args, **kwargs)
    142
    143         return wrapped

~\Anaconda3\lib\site-packages\speasy\core\dataprovider.py in _inventory(self, provider_name)
     51     @Proxyfiable(request=GetInventory, arg_builder=_get_inventory_args)
     52     def _inventory(self, provider_name) -> SpeasyIndex:
---> 53         return self.build_inventory(SpeasyIndex(provider=provider_name, name=provider_name, uid=provider_name,
     54                                                 meta={'build_date': datetime.utcnow().isoformat()}))
     55

~\Anaconda3\lib\site-packages\speasy\webservices\ssc\__init__.py in build_inventory(self, root)
     77
     78     def build_inventory(self, root: SpeasyIndex):
---> 79         inv = list(map(make_index, self.get_observatories()))
     80         root.Trajectories = SpeasyIndex(name='Trajectories', provider='ssc', uid='Trajectories',
     81                                         meta={item.Id: item for item in inv})

~\Anaconda3\lib\site-packages\speasy\core\cache\_function_cache.py in wrapped(disable_cache, force_refresh, *args, **kwargs)
     50                 return self.add_to_cache(cache_entry, function(*args, **kwargs))
     51             else:
---> 52                 return self.get_from_cache(cache_entry) or self.add_to_cache(cache_entry, function(*args, **kwargs))
     53
     54         return wrapped

~\Anaconda3\lib\site-packages\speasy\webservices\ssc\__init__.py in get_observatories(self)
     87         if not res.ok:
     88             return None
---> 89         return res.json()['Observatory'][1]
     90
     91     def version(self, product):

TypeError: list indices must be integers or slices, not str

In [3]:

**Comment by jeandet** [comment]
@Nfargette, the Speasy cache server got blocked by NASA's servers, they are working on it. It should be fixed soon :crossed_fingers: .

**Comment by jeandet** [comment]
@Nfargette , it is fixed for now.

**Comment by Nfargette** [comment]
Top merci !
