### ISSUE TITLE
It will be helpful to have the possibility to get a catalog as a pandas dataframe, for example: amda.get_catalog(...).to_dataframe()

### ISSUE THREAD

**Issue by menouarazib** [SciQLop/speasy#35]
* Space Physics WebServices Client version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by jeandet** [comment]
@menouarazib this is implemented with #36, you can git it a try by installing this branch before PR get merged.
You can use `pip install git+https://github.com/jeandet/speasy@catalog_to_dataframe`.
