### ISSUE TITLE
amda.list_user_parameters() is not up to date

### ISSUE THREAD

**Issue by menouarazib** [SciQLop/speasy#39]
* Space Physics WebServices Client version: 0.10.1
* Python version: 3.10
* Operating System: Windows 10

### Description

I'm using `amda.list_user_parameters()`  to get the list of my parameters, it works very well. The problem is that when I create a new parameter directly with "http://amda.cdpp.eu/" and then if I run the same method the returned list of parameters is not up to date.

### What I Did

```
config.amda_username.set('...')
config.amda_password.set('....')
print(amda.list_user_parameters())
```

**Comment by jeandet** [comment]
This is likely due to the cache see here:
https://speasy.readthedocs.io/en/latest/user/amda/amda.html#amda-cache-retention
Maybe you can reduce it to less than 5 minutes so you won't wait much if you call many times list_user_parameters but also see faster modifications.

**Comment by jeandet** [comment]
@menouarazib is that OK, can I close the issue or this is a different bug?

**Comment by menouarazib** [comment]
@jeandet thanks for your reply, yes you can close the issue.
