### ISSUE TITLE
I can't find how to set amda username and password with Speasy 1.0.0

### ISSUE THREAD

**Issue by menouarazib** [SciQLop/speasy#66]
* Space Physics WebServices Client version:
* Python version:
* Operating System:

### Description

I can't find how to set amda username and password

### What I Did

```
spz.config.amda_username.set('testKernel')
spz.config.amda_password.set('amda')
```

**Comment by jeandet** [comment]
With 1.0 release the config module has changed a bit, you should use:
```Python
config.amda.username.set('testKernel') 
config.amda.password.set('amda') 
```
As explained here: https://speasy.readthedocs.io/en/latest/user/amda/amda.html#amda-user-login
