### ISSUE TITLE
ImportError: cannot import name 'LegacyVersion' from 'packaging.version' 

### ISSUE THREAD

**Issue by brenard-irap** [SciQLop/speasy#78]
As you can see at https://packaging.pypa.io/en/stable/changelog.html, "LegacyVersion" has been removed from the last version (22.0) of packaging.

Unfortunately, Speasy uses it in [speasy/core/cache/version.py](https://github.com/SciQLop/speasy/blob/588a37112088dd1de615e170c9a71e8341e01948/speasy/core/cache/version.py)

So, we have an exception during the import:

`ImportError: cannot import name 'LegacyVersion' from 'packaging.version' (C:\Users\benjamin.renard\Documents\AMDA\cu2022_3_10_venv\lib\site-packages\packaging\version.py)`

I have downgrade packaging to version 21.3 to fix the issue

**Comment by jeandet** [comment]
I'll look into this ASAP.
